apiVersion: 1

contactPoints:
  - orgId: 1
    name: AeroNet Notifier
    receivers:
      - uid: aeronet-notifier-webhook
        type: webhook
        settings:
          url: http://notifier:8001/alert/grafana
          httpMethod: POST
          title: |
            {{ template "default.title" . }}
          message: |
            {{ template "default.message" . }}

policies:
  - orgId: 1
    receiver: AeroNet Notifier
    group_by: ['grafana_folder', 'alertname']
    group_wait:      30s
    group_interval:  5m
    repeat_interval: 4h
    routes:
      - receiver: AeroNet Notifier
        matchers:
          - severity =~ "critical|warning"
