apiVersion: 1

datasources:
  - name: AeroNet PostgreSQL
    type: postgres
    uid: aeronet-pg
    url: postgres:5432
    user: aeronet
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      database: aeronet
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: false
    editable: false
