apiVersion: 1

datasources:
  - name: AeroNet Prometheus
    type: prometheus
    uid: aeronet-prom
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: 15s
    editable: false
