global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    site: aeronet-os

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'aeronet-postgres'

  - job_name: 'api-gateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api-gateway:8000']

  - job_name: 'collector'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['collector:8003']

  - job_name: 'enroller'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['enroller:8002']
